### ISSUE TITLE
Listener encounters 403 status when attempting to join

### ISSUE THREAD

**Issue by titswort** [Pogify/pogify#13]
---
name: TotalSundae
about: End User cannot connect to my session
title: 'Listener encounters 403 status when attempting to join

---

**Describe the bug**
I've been troubleshooting a problem that a friend of mine has encountered. In the README section one of the bugs that seems to have gone unfixed is 'the start and join session buttons sometimes don't work'. The user in question can log into spotify, and attempt to join my session, but when they click the 'join session' button is becomes uninteractible and their js console describes the following error:  

Failed to load resource: the server responded with a status of 403 ()    api.spotify.com/v1/me/player/play?device_id=undefined:1
createError.js:16 Uncaught (in promise) Error: Request failed with status code 403
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)

**To Reproduce**
1. Go to 'any session link, log in'
2. Click on 'join session'
3. Scroll down to 'open the console with f12'

**Expected behavior**
It is expected that once the user joins the session that they would be able to listen to the music that the host is currently playing. They have the ability to join the 'Pogify Listener' device in the spotify desktop app, but it will only play whatever track they have current queued up.

**Desktop (please complete the following information):**
 - OS: Windows 10, v2004
 - Browser: Chrome
 - Version: Latest

**Additional context**
I'm also submitting a bug report to spotify considering the problem might lie outside of this app. It should be noted that the user cannot see what their friends are currently listening to, because they won't update. Any knowledge related to why this might be is appreciated. We've gone through the simple steps of reinstallation, firewall disabling, restarting clients, etc.

**Comment by jeongY-Cho** [comment]
Thanks for your bug report. 

A 403 status indicates that the request is forbidden by Spotify and is not necessarily an issue caused by Pogify. The list of reasons for a 403 response is available at the Spotify Developer site (q.v https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-object). 

If you would like (and to satisfy my own curiosity), if you can provide a HAR dump of network calls, I can probably get more information on what caused the error. Attach the HAR file to a reply (you might need to zip it first). 

PS.If you need help generating a HAR file, [this link](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) can help you.

**Comment by r2dev2bb8** [comment]
Hello, I encountered a similar question on Spotify's official help page and the data said that the user with trouble was using free Spotify. The current Pogify can't support free Spotify accounts since doing so would involve violating Spotify's developer TOS.
