### ISSUE TITLE
Transition to Spotify Web API in order to support a possible mobile app and/or mobile browser

### ISSUE THREAD

**Issue by Redseb** [Pogify/pogify#60]
**Do you understand that Pogify does not support Safari, Mobile, or Spotify Free at this time?**
(Yes)

By using the [Spotify Web API](https://developer.spotify.com/documentation/web-api/) we should be able to overcome to limitations listed in the README. The Spotify Web API allows for mobile browser and could even work in a React Native app. An example of it's usage in such an app is [Hour Power](https://github.com/brentvatne/hour-power) which utilises [spotify-web-api-js](https://github.com/JMPerez/spotify-web-api-js) as a wrapper.

Of course the issue still remains that you can't watch a twitch stream and play Spotify at the same time (one or the other pauses), however users will still be able to play Spotify on their phone and watch a stream on their PCs for example.

_Let me know what you think_ ☺️

**Comment by Arno500** [comment]
The Web API does not allow playing. They are just a collection of endpoints where we can remote control other apps and query the current state.
Also, they don't allow the use of their -private- WebSocket API, thus we can't get realtime info if we don't poll (and we can't, given the number of users we target).

But since we only only do "remoting" on the viewer side, this may be doable. If we can't get it to work on mobile, I'm not sure of the added value tho.

**Comment by Redseb** [comment]
Yeah I'm not sure how big the benefit would be but we can definitely remote control a background playing Spotify app (play, pause, set position in song) using spotify-web-api-js. 

Either way probably not a priority!
